import { CausalDiagnostic, CityState, TileType } from './types';

export function calculateCausalDiagnostics(state: CityState): CausalDiagnostic[] {
  const diagnostics: CausalDiagnostic[] = [];
  const day = state.day;
  const add = (diagnostic: Omit<CausalDiagnostic, 'id' | 'day'>) => diagnostics.push({ ...diagnostic, id: `${diagnostic.category.toLowerCase()}-${diagnostics.length + 1}-${day}`, day });

  if (state.unemploymentRate > 12) add({ category: 'POPULATION', severity: 'WARNING', title: 'Pengangguran meningkat', explanation: 'Jumlah warga yang mencari kerja lebih besar daripada kapasitas pekerjaan aktif.', recommendation: 'Periksa job tiers dan tambahkan sektor yang sesuai dengan pendidikan warga.', value: state.unemploymentRate, threshold: 12 });
  if ((state.averageCommuteTime ?? 0) > 25) add({ category: 'TRAFFIC', severity: 'WARNING', title: 'Waktu commute tinggi', explanation: 'Perjalanan kerja terlalu lama; periksa queue pressure, kapasitas jalan, dan coverage transit.', recommendation: 'Cari koridor dengan queue pressure tertinggi lalu tambahkan arterial atau transit.', value: state.averageCommuteTime, threshold: 25 });
  if ((state.congestionIndex ?? 0) > 50) add({ category: 'TRAFFIC', severity: 'CRITICAL', title: 'Koridor metropolitan jenuh', explanation: 'Kemacetan sudah memengaruhi perjalanan, freight, dan response time layanan.', recommendation: 'Aktifkan Traffic overlay dan tangani simpang dengan lane load tertinggi.', value: state.congestionIndex, threshold: 50 });
  if ((state.marketHealth ?? 100) < 45) add({ category: 'ECONOMY', severity: 'WARNING', title: 'Market health melemah', explanation: 'Supply barang dan reliability logistik tidak cukup untuk memenuhi permintaan kota.', recommendation: 'Periksa commodity stock dan pastikan warehouse serta cargo access terhubung.', value: state.marketHealth ?? 0, threshold: 45 });
  if ((state.officeUtilization ?? 1) < 0.72 && (state.officeDemand ?? 0) > 0) add({ category: 'ECONOMY', severity: 'WARNING', title: 'Kantor kurang terisi', explanation: 'Permintaan pekerjaan berpengetahuan belum seimbang dengan supply kantor. Naikkan pendidikan, akses transit, atau buka kawasan office dekat pusat aktivitas.', recommendation: 'Prioritaskan pendidikan dan transit sebelum menambah office supply.', value: Math.round((state.officeUtilization ?? 0) * 100), threshold: 72 });
  if ((state.productionEfficiency ?? 1) < 0.8) add({ category: 'ECONOMY', severity: 'WARNING', title: 'Input industri kurang', explanation: 'Rantai produksi kehilangan MATERIALS/FUEL atau akses freight. Tambahkan highway, warehouse, cargo terminal, atau kontrak import yang sesuai.', recommendation: 'Cari commodity dengan shortage terbesar dan tambahkan kapasitas input.', value: Math.round((state.productionEfficiency ?? 0) * 100), threshold: 80 });
  if ((state.tradeImportCapacity ?? 0) > 0 && (state.freightReliability ?? 100) < 65) add({ category: 'ECONOMY', severity: 'WARNING', title: 'Kontrak import belum efektif', explanation: 'Kapasitas kontrak tersedia, tetapi jaringan jalan, warehouse, atau distribusi lokal masih menahan reliability freight.', recommendation: 'Perbaiki akses jalan antara terminal, warehouse, dan kawasan komersial.', value: state.freightReliability ?? 0, threshold: 65 });
  if ((state.climateFireRisk ?? 1) > 1.35) add({ category: 'ENVIRONMENT', severity: 'WARNING', title: 'Risiko kebakaran iklim meningkat', explanation: 'Cuaca panas/kering menaikkan risiko wildfire. Periksa coverage pemadam, water reserve, dan kepadatan bangunan.', recommendation: 'Siapkan water reserve dan tambah coverage pemadam di tepi kota.', value: state.climateFireRisk, threshold: 1.35 });
  if ((state.income ?? 0) < (state.expenses ?? 0)) add({ category: 'ECONOMY', severity: 'CRITICAL', title: 'Anggaran operasional negatif', explanation: 'Pengeluaran harian melebihi pendapatan. Tunda ekspansi atau ubah pajak dan prioritas layanan.', recommendation: 'Hentikan ekspansi, cek maintenance terbesar, lalu stabilkan operating budget.', value: state.income - state.expenses, threshold: 0 });
  if ((state.serviceResponseQuality ?? 100) < 60) add({ category: 'SERVICES', severity: 'CRITICAL', title: 'Response layanan melemah', explanation: 'Kemacetan, kapasitas facility, atau kondisi depot membuat layanan darurat terlambat.', recommendation: 'Buka Dispatch overlay dan prioritaskan fasilitas dengan queue atau depot condition terburuk.', value: state.serviceResponseQuality ?? 0, threshold: 60 });
  if ((state.pollutionAverage ?? 0) > 35) add({ category: 'ENVIRONMENT', severity: 'WARNING', title: 'Polusi kota tinggi', explanation: 'Industri, traffic, dan tata guna lahan menurunkan kesehatan serta desirability.', recommendation: 'Pisahkan industri dari hunian dan tambahkan green buffer atau transit.', value: state.pollutionAverage, threshold: 35 });

  const abandoned = state.grid.flat().find((tile) => tile.abandoned && [TileType.RESIDENTIAL, TileType.COMMERCIAL, TileType.INDUSTRIAL].includes(tile.type));
  if (abandoned) add({ category: 'BUILDING', severity: 'WARNING', title: 'Bangunan terbengkalai', explanation: 'Periksa listrik, air, road access, demand, disaster impact, dan kualitas lingkungan di lokasi ini.', recommendation: 'Fokus tile ini untuk melihat penyebab abandonment secara langsung.', value: 1, location: { x: abandoned.x, y: abandoned.y } });
  const housingPressure = state.grid.flat().find((tile) => tile.type === TileType.RESIDENTIAL && (tile.rentPressure ?? 0) >= 2.2);
  if (housingPressure) add({ category: 'BUILDING', severity: 'WARNING', title: 'Tekanan sewa perumahan', explanation: 'Sewa melebihi kemampuan rumah tangga di parcel ini. Tambahkan density yang lebih tinggi, transit, service coverage, atau residential supply.', recommendation: 'Fokus parcel ini dan pertimbangkan medium/high density dengan transit.', value: housingPressure.rentPressure ?? 0, threshold: 2.2, location: { x: housingPressure.x, y: housingPressure.y } });
  return diagnostics.slice(0, 12);
}
