export type SupportedLanguage = 'id' | 'en';

export interface LocalizationCatalog {
  language: SupportedLanguage;
  fallbackLanguage: SupportedLanguage;
  messages: Record<string, string>;
  fallbackMessages: Record<string, string>;
}

export const DEFAULT_LOCALIZATION: LocalizationCatalog = {
  language: 'id',
  fallbackLanguage: 'en',
  messages: {
    'app.continue': 'Lanjutkan Kota',
    'app.newCity': 'Kota Baru',
    'app.saveRecovery': 'Pemulihan Simpanan',
    'app.loadImport': 'Muat / Impor',
    'app.settings': 'Pengaturan',
    'app.browserHint': 'Chromium Desktop · Simpanan tersimpan lokal di browser',
    'menu.title': 'Menu Pengelolaan',
    'menu.cityInformation': 'Informasi Kota',
    'menu.economy': 'Ekonomi & Kas',
    'menu.technology': 'Pohon Teknologi',
    'menu.policies': 'Kebijakan Daerah',
    'menu.districts': 'Perencana Distrik',
    'menu.objectives': 'Tujuan & Misi',
    'menu.saveLoad': 'Simpan / Muat Kota',
    'menu.settings': 'Pengaturan Kota',
    'menu.quitNewCity': 'Keluar & Kota Baru',
    'save.title': 'Pengelolaan Simpan & Muat Kota',
    'save.subtitle': 'Penyimpanan Sesi & Arsip Slot',
    'save.designation': 'Nama Kota:',
    'save.newGame': 'Kota Baru',
    'save.portableBackup': 'Cadangan Portabel',
    'save.importValidated': 'Impor divalidasi sebelum menimpa slot.',
    'save.importJson': 'Impor JSON',
    'save.closeImport': 'Tutup impor',
    'save.emptySlot': 'Slot Simpan Kosong',
    'save.save': 'Simpan',
    'save.load': 'Muat',
    'save.export': 'Ekspor JSON Simpan',
    'save.delete': 'Hapus Slot Simpan',
    'save.confirmation': 'Konfirmasi Diperlukan',
    'save.cancel': 'Batal',
    'save.confirm': 'Konfirmasi',
    'app.performanceWarning': 'Kualitas visual diturunkan untuk menjaga kelancaran.',
    'nav.roads': 'Jalan',
    'nav.zoning': 'Zonasi',
    'nav.utilities': 'Utilitas',
    'nav.services': 'Layanan',
    'nav.transit': 'Transit',
    'nav.logistics': 'Logistik',
    'nav.terrain': 'Medan',
    'tool.select': 'Pilih',
    'tool.bulldoze': 'Hapus',
    'tool.search': 'Cari tool',
    'tool.category': 'Kategori Bangun',
    'sidebar.basic': 'Dasar',
    'sidebar.advanced': 'Lanjutan',
    'tool.localRoad': 'Jalan Lokal',
    'tool.arterial': 'Arteri',
    'tool.highway': 'Jalan Tol',
    'tool.tunnel': 'Terowongan',
    'tool.roadWorks': 'Pekerjaan Jalan',
    'tool.lowResidential': 'Hunian Rendah',
    'tool.mediumResidential': 'Hunian Sedang',
    'tool.highResidential': 'Hunian Tinggi',
    'tool.commercial': 'Komersial',
    'tool.office': 'Perkantoran',
    'tool.industrial': 'Industri',
    'tool.powerPlant': 'Pembangkit Listrik',
    'tool.waterPump': 'Pompa Air',
    'tool.fireStation': 'Pemadam Kebakaran',
    'tool.policeStation': 'Kantor Polisi',
    'tool.clinic': 'Klinik Medis',
    'tool.school': 'Sekolah',
    'tool.wastePlant': 'Pengolahan Sampah',
    'tool.park': 'Taman Kota',
    'tool.parking': 'Area Parkir',
    'tool.floodBarrier': 'Tanggul Banjir',
    'tool.reservoir': 'Waduk Air',
    'tool.busDepot': 'Depot Bus',
    'tool.tramStation': 'Stasiun Trem',
    'tool.busStop': 'Halte Bus',
    'tool.tramStop': 'Pemberhentian Trem',
    'tool.linePlanner': 'Perencana Rute',
    'tool.warehouse': 'Gudang Logistik',
    'tool.cargoTerminal': 'Terminal Kargo',
    'tool.raise': 'Naikkan Tanah',
    'tool.lower': 'Turunkan Tanah',
    'tool.level': 'Ratakan Tanah',
    'tool.smooth': 'Haluskan Tanah',
    'pulse.title': 'Denyut Kota',
    'pulse.cityInfo': 'Info Kota',
    'pulse.detail': 'Detail',
    'pulse.focus': 'Fokus',
    'pulse.next': 'Berikutnya',
    'pulse.stable': 'Kota berjalan stabil. Gunakan Info Kota untuk memantau kebutuhan, jaringan, dan perkembangan warga secara mendalam.',
    'forecast.capacity': 'Kapasitas',
    'forecast.households': 'Rumah Tangga',
    'forecast.jobs': 'Lapangan Kerja',
    'forecast.traffic': 'Beban Lalu Lintas',
    'forecast.tax': 'Pajak',
    'forecast.maintenance': 'Biaya Perawatan',
    'forecast.pollution': 'Polusi',
    'info.title': 'Informasi Kota',
    'info.subtitle': 'Simulasi Warga & Tata Kota 2.0',
    'info.overview': 'Ringkasan',
    'info.citizens': 'Warga',
    'info.economy': 'Ekonomi',
    'info.services': 'Layanan',
    'info.traffic': 'Lalu Lintas',
    'info.environment': 'Lingkungan',
    'summary.executiveSummary': 'Ringkasan Eksekutif Kota',
    'summary.population': 'Populasi',
    'summary.dailyIncome': 'Pendapatan Harian',
    'summary.happiness': 'Kebahagiaan Warga',
    'summary.trafficCongestion': 'Indeks Kemacetan',
    'summary.serviceCapacity': 'Kapasitas Layanan',
    'summary.topIssue': 'Masalah Terbesar',
    'summary.nextTarget': 'Target Berikutnya',
    'summary.beforeAfter': 'Ilustrasi Dampak Sistem',
    'summary.illustrativeNote': 'Ilustrasi desain sistem; bukan counterfactual atau hasil pengukuran sebelum/sesudah.',
    'summary.noIssue': 'Tidak ada masalah kritis. Kota berjalan stabil.',
    'info.cityDemands': 'Kebutuhan Kota',
    'info.demandTrends': 'Tren Kebutuhan & Kota',
    'info.disasterResponse': 'Respons Bencana Alam',
    'info.keyMetrics': 'Metrik Utama',
    'info.demographicSnapshot': 'Ringkasan Demografi',
    'infoViews.title': 'Tampilan Info',
    'infoViews.traffic': 'Lalu Lintas',
    'infoViews.roadCondition': 'Kondisi Jalan',
    'infoViews.roadHierarchy': 'Hierarki Jalan',
    'infoViews.publicTransit': 'Transit Publik',
    'infoViews.transitRoutes': 'Rute Transit',
    'infoViews.emergencyDispatch': 'Respons Darurat',
    'infoViews.serviceResponse': 'Waktu Respons Layanan',
    'infoViews.power': 'Listrik',
    'infoViews.water': 'Air',
    'infoViews.waste': 'Sampah',
    'infoViews.health': 'Kesehatan',
    'infoViews.education': 'Pendidikan',
    'infoViews.fireSafety': 'Keselamatan Kebakaran',
    'infoViews.policeCrime': 'Polisi & Kriminalitas',
    'infoViews.landValue': 'Nilai Lahan',
    'infoViews.pollution': 'Polusi',
    'infoViews.noise': 'Kebisingan',
    'infoViews.happiness': 'Kebahagiaan',
    'infoViews.incidents': 'Insiden',
    'infoViews.disasters': 'Bencana Alam',
    'infoViews.naturalResources': 'Sumber Daya Alam',
    'infoViews.hydrology': 'Air Permukaan & Banjir',
    'infoViews.districts': 'Kebijakan Distrik',
    'infoViews.resourcesLegend': 'Legenda Sumber Daya',
    'infoViews.fertileLand': 'Lahan Subur (Pertanian)',
    'infoViews.forest': 'Hutan (Industri Kayu)',
    'infoViews.oreMinerals': 'Mineral Bijih (Pertambangan)',
    'infoViews.oilReserves': 'Cadangan Minyak (Pengeboran)',
    'infoViews.responseTime': 'Waktu respons (menit)',
    'infoViews.transitRouteNetwork': 'Jaringan rute transit',
    'infoViews.emergencyDispatchPaths': 'Jalur respons darurat',
    'infoViews.fire': 'Pemadam',
    'infoViews.medical': 'Medis',
    'infoViews.police': 'Polisi',
    'metric.households': 'Rumah Tangga',
    'metric.householdSatisfaction': 'Kepuasan Rumah Tangga',
    'metric.treasury': 'Kas Kota',
    'metric.landUseSuitability': 'Kesesuaian Tata Guna Lahan',
    'metric.persistentParcels': 'Parcel Persisten',
    'metric.developedPrivateLots': 'Lot Terbangun / Privat',
    'metric.averageLotSize': 'Ukuran Lot Rata-rata',
    'metric.mixedUseBlocks': 'Blok Campuran',
    'metric.mixedUseFloors': 'Lantai Campuran',
    'metric.mixedUseJobs': 'Lapangan Kerja Campuran',
    'metric.netIncome': 'Pendapatan Bersih',
    'metric.municipalDebt': 'Utang Daerah',
    'metric.activeBackgroundRegions': 'Wilayah Aktif / Latar',
    'metric.recoveryProjects': 'Proyek Pemulihan',
    'metric.tradeContracts': 'Kontrak Perdagangan',
    'metric.importCapacity': 'Kapasitas Impor',
    'metric.exportCapacity': 'Kapasitas Ekspor',
    'metric.exportRevenue': 'Pendapatan Ekspor',
    'metric.citySpecialization': 'Spesialisasi Kota',
    'metric.activeDisasters': 'Bencana Aktif',
    'metric.recoveryLoad': 'Beban Pemulihan',
    'metric.roadRecoveryTick': 'Pemulihan Jalan / Tick',
    'metric.resolvedThisTick': 'Selesai Tick Ini',
    'metric.happinessPenalty': 'Penalti Kebahagiaan',
    'metric.seasonWeather': 'Musim / Cuaca',
    'metric.temperature': 'Suhu',
    'metric.precipitation': 'Curah Hujan',
    'metric.population': 'Populasi',
    'metric.happiness': 'Kebahagiaan',
    'metric.totalHouseholds': 'Total Rumah Tangga',
    'metric.employedWorkforce': 'Angkatan Kerja Terserap',
    'metric.employedCitizens': 'Warga Bekerja',
    'metric.unemploymentRate': 'Tingkat Pengangguran',
    'metric.avgDailySalary': 'Rata-rata Upah Harian',
    'settings.title': 'Pengaturan Game',
    'settings.gameplay': 'Gameplay',
    'settings.graphics': 'Grafis',
    'settings.audio': 'Audio',
    'settings.controls': 'Kontrol',
    'settings.accessibility': 'Aksesibilitas',
    'settings.rules': 'Aturan Permainan',
    'settings.difficulty': 'Tingkat Kesulitan',
    'settings.autosave': 'Simpan Otomatis',
    'settings.graphicsTitle': 'Pengaturan Grafis',
    'settings.shadowQuality': 'Kualitas Bayangan',
    'settings.antiAliasing': 'Anti-aliasing',
    'settings.renderScale': 'Skala Render',
    'settings.dayNightCycle': 'Siklus Siang/Malam',
    'settings.trafficDensity': 'Kepadatan Lalu Lintas',
    'settings.vegetationDensity': 'Kepadatan Vegetasi',
    'settings.vsyncTitle': 'V-Sync & batas frame',
    'settings.vsyncInfo': 'Dikelola oleh browser melalui requestAnimationFrame. Opsi manual disembunyikan sampai renderer memiliki frame cap yang benar-benar dapat dikendalikan.',
    'settings.audioTitle': 'Pengaturan Audio',
    'settings.sfxVolume': 'Volume Efek Suara',
    'settings.musicVolume': 'Volume Musik & Suasana',
    'settings.soundscapeTitle': 'Soundscape Suasana Kota',
    'settings.soundscapeInfo': 'Volume Musik mengontrol musik pad dan suasana kota prosedural Web Audio. Volume Efek mengontrol suara klik, pembangunan, perobohan, dan sirine.',
    'settings.controlsTitle': 'Kontrol & Pintasan Keyboard',
    'settings.accessibilityTitle': 'Aksesibilitas & Dukungan',
    'settings.language': 'Bahasa',
    'settings.uiScale': 'Ukuran UI',
    'settings.reducedMotion': 'Kurangi Animasi',
    'settings.adaptiveQuality': 'Kualitas Adaptif',
    'settings.experimental': 'Fitur Eksperimental',
    'settings.highContrast': 'Kontras Tinggi',
    'settings.colorblind': 'Bantuan Penglihatan Warna',
    'settings.none': 'Tidak ada',
    'settings.qualityNote': 'Kualitas adaptif menurunkan detail visual saat frame rate turun. Hasil simulasi dan angka ekonomi tidak berubah.',
    'settings.exportDiagnostic': 'Ekspor Laporan Diagnostik',
    'settings.reset': 'Atur Ulang Pengaturan',
    'settings.repeatTutorial': 'Ulangi Panduan',
    'settings.toggleOn': 'aktif',
    'settings.toggleOff': 'nonaktif',
    'settings.easy': 'Mudah (Bonus Dana & Pertumbuhan)',
    'settings.normal': 'Normal (Keseimbangan Standar)',
    'settings.hard': 'Sulit (Utilitas & Kebutuhan Ketat)',
    'settings.applyClose': 'Terapkan & Tutup',
    'missions.title': 'Tujuan Kota & Lencana',
    'missions.subtitle': 'Tantangan Milestone & Pencapaian',
    'missions.tab': 'Tujuan & Hibah',
    'achievements.tab': 'Pencapaian Sipil',
    'scenarios.tab': 'Skenario Kampanye',
    'missions.grant': 'Hibah',
    'missions.completed': 'Selesai',
    'missions.claim': 'Klaim Hadiah',
    'missions.progress': 'Berlangsung',
    'scenario.start': 'Mulai',
    'scenario.active': 'Aktif',
    'policies.title': 'Arahan Kebijakan Daerah',
    'policies.subtitle': 'Tetapkan Peraturan · Kebijakan Aktif',
    'policies.free': 'Bebas Biaya',
    'policies.apply': 'Terapkan Kebijakan',
    'policies.locked': 'Terkunci',
    'policies.benefits': 'Diuntungkan',
    'policies.costBearer': 'Menanggung biaya',
    'policies.ruleEffect': 'Efek rule engine',
    'policies.longTerm': 'Jangka panjang',
    'policies.metric': 'Metrik evaluasi',
    'tech.title': 'Pohon Teknologi & Inovasi Kota',
    'tech.subtitle': 'Teliti Teknologi Prasyarat · Milestone Saat Ini',
    'tech.requires': 'Membutuhkan',
    'tech.researched': 'Sudah diteliti',
    'tech.prerequisiteLocked': 'Prasyarat Terkunci',
    'tech.milestoneLocked': 'Milestone Terkunci',
    'tech.insufficientFunds': 'Dana Tidak Cukup',
    'tech.research': 'Teliti Teknologi',
    'districts.title': 'Perencana Distrik',
    'districts.subtitle': 'Identitas spasial & kebijakan lokal',
    'districts.create': 'Buat distrik',
    'districts.name': 'Nama',
    'districts.localPolicy': 'Kebijakan lokal',
    'districts.radius': 'Radius',
    'districts.place': 'Tempatkan di Peta',
    'districts.existing': 'Distrik yang ada',
    'districts.total': 'total',
    'districts.empty': 'Belum ada distrik. Buat satu untuk memberi identitas dan kebijakan lokal pada kawasan kota.',
    'inspector.title': 'Inspeksi Petak',
    'inspector.growthAdvisor': 'Advisor Pertumbuhan',
    'inspector.occupancy': 'Okupansi',
    'inspector.demand': 'Permintaan',
    'inspector.capacity': 'Kapasitas',
    'inspector.density': 'Kepadatan',
    'inspector.bulldoze': 'Gusur Petak',
    'inspector.intersectionControl': 'Pengaturan Simpang',
    'inspector.auto': 'Otomatis',
    'inspector.signal': 'Sinyal',
    'inspector.stopSigns': 'Rambu Berhenti',
    'inspector.roundabout': 'Bundaran',
    'metric.consumerDemand': 'Permintaan Konsumen',
    'metric.goodsDemand': 'Permintaan Barang',
    'metric.officeDemand': 'Permintaan Perkantoran',
    'metric.freightDemand': 'Permintaan Kargo',
    'traffic.commuteFlow': 'Arus Lalu Lintas & Komuter',
    'traffic.averageFlow': 'Kelancaran Lalu Lintas Rata-Rata',
    'traffic.congestionIndex': 'Indeks Kemacetan',
    'traffic.avgCommuteTime': 'Waktu Komuter Rata-Rata',
    'traffic.parkingDemand': 'Kebutuhan Parkir',
    'traffic.transitNetwork': 'Jaringan Transit Publik',
    'metric.desirability': 'Daya Tarik Kota',
    'metric.preparedness': 'Kesiapsiagaan Bencana',
    'scenario.completed': 'Selesai',
    'scenario.monitoring': 'Pemantauan',
    'spec.balanced': 'Seimbang',
  },
  fallbackMessages: {
    'app.continue': 'Continue City',
    'app.newCity': 'New City',
    'app.saveRecovery': 'Save Recovery',
    'app.loadImport': 'Load / Import',
    'app.settings': 'Settings',
    'app.browserHint': 'Desktop Chromium · Saves are stored locally in the browser',
    'menu.title': 'Management Menu',
    'menu.cityInformation': 'City Information',
    'menu.economy': 'Economy & Treasury',
    'menu.technology': 'Technology Tree',
    'menu.policies': 'Municipal Policies',
    'menu.districts': 'District Planner',
    'menu.objectives': 'Objectives & Missions',
    'menu.saveLoad': 'Save / Load Game',
    'menu.settings': 'Game Settings',
    'menu.quitNewCity': 'Quit & New City',
    'save.title': 'City Save & Load Management',
    'save.subtitle': 'Session Storage & Slot Archives',
    'save.designation': 'City Designation:',
    'save.newGame': 'New Game',
    'save.portableBackup': 'Portable backup',
    'save.importValidated': 'Import is validated before overwriting a slot.',
    'save.importJson': 'Import JSON',
    'save.closeImport': 'Close import',
    'save.emptySlot': 'Empty Save Slot',
    'save.save': 'Save',
    'save.load': 'Load',
    'save.export': 'Export Save JSON',
    'save.delete': 'Delete Save Slot',
    'save.confirmation': 'Confirmation Required',
    'save.cancel': 'Cancel',
    'save.confirm': 'Confirm',
    'app.performanceWarning': 'Visual quality was reduced to keep the game smooth.',
    'nav.roads': 'Roads',
    'nav.zoning': 'Zoning',
    'nav.utilities': 'Utilities',
    'nav.services': 'Services',
    'nav.transit': 'Transit',
    'nav.logistics': 'Logistics',
    'nav.terrain': 'Terrain',
    'tool.select': 'Select',
    'tool.bulldoze': 'Bulldoze',
    'tool.search': 'Search tools',
    'tool.category': 'Build category',
    'sidebar.basic': 'Basic',
    'sidebar.advanced': 'Advanced',
    'tool.localRoad': 'Local Road',
    'tool.arterial': 'Arterial',
    'tool.highway': 'Highway',
    'tool.tunnel': 'Tunnel',
    'tool.roadWorks': 'Road Works',
    'tool.lowResidential': 'Low-density Residential',
    'tool.mediumResidential': 'Medium-density Residential',
    'tool.highResidential': 'High-density Residential',
    'tool.commercial': 'Commercial',
    'tool.office': 'Office',
    'tool.industrial': 'Industrial',
    'tool.powerPlant': 'Power Plant',
    'tool.waterPump': 'Water Pump',
    'tool.fireStation': 'Fire Station',
    'tool.policeStation': 'Police HQ',
    'tool.clinic': 'Clinic',
    'tool.school': 'School',
    'tool.wastePlant': 'Waste Plant',
    'tool.park': 'Park',
    'tool.parking': 'Parking',
    'tool.floodBarrier': 'Flood Barrier',
    'tool.reservoir': 'Reservoir',
    'tool.busDepot': 'Bus Depot',
    'tool.tramStation': 'Tram Station',
    'tool.busStop': 'Bus Stop',
    'tool.tramStop': 'Tram Stop',
    'tool.linePlanner': 'Line Planner',
    'tool.warehouse': 'Warehouse',
    'tool.cargoTerminal': 'Cargo Terminal',
    'tool.raise': 'Raise',
    'tool.lower': 'Lower',
    'tool.level': 'Level',
    'tool.smooth': 'Smooth',
    'pulse.title': 'City Pulse',
    'pulse.cityInfo': 'City Info',
    'pulse.detail': 'Details',
    'pulse.focus': 'Focus',
    'pulse.next': 'Next',
    'pulse.stable': 'The city is stable. Use City Info to monitor demand, networks, and citizen development in depth.',
    'forecast.capacity': 'Capacity',
    'forecast.households': 'Households',
    'forecast.jobs': 'Jobs',
    'forecast.traffic': 'Traffic',
    'forecast.tax': 'Tax',
    'forecast.maintenance': 'Maintenance',
    'forecast.pollution': 'Pollution',
    'info.title': 'City Information',
    'info.subtitle': 'Citizen & Urban Simulation 2.0',
    'info.overview': 'Overview',
    'info.citizens': 'Citizens',
    'info.economy': 'Economy',
    'info.services': 'Services',
    'info.traffic': 'Traffic',
    'info.environment': 'Environment',
    'summary.executiveSummary': 'City Executive Summary',
    'summary.population': 'Population',
    'summary.dailyIncome': 'Daily Income',
    'summary.happiness': 'Citizen Happiness',
    'summary.trafficCongestion': 'Congestion Index',
    'summary.serviceCapacity': 'Service Capacity',
    'summary.topIssue': 'Top Issue',
    'summary.nextTarget': 'Next Target',
    'summary.beforeAfter': 'Illustrative System Impact',
    'summary.illustrativeNote': 'Illustrative system design; not a counterfactual or a measured before/after result.',
    'summary.noIssue': 'No critical issues. The city operates smoothly.',
    'info.cityDemands': 'City Demands',
    'info.demandTrends': 'Demand & City Trends',
    'info.disasterResponse': 'Natural Disaster Response',
    'info.keyMetrics': 'Key Metrics',
    'info.demographicSnapshot': 'Demographic Snapshot',
    'infoViews.title': 'Info Views',
    'infoViews.traffic': 'Traffic',
    'infoViews.roadCondition': 'Road Condition',
    'infoViews.roadHierarchy': 'Road Hierarchy',
    'infoViews.publicTransit': 'Public Transit',
    'infoViews.transitRoutes': 'Transit Routes',
    'infoViews.emergencyDispatch': 'Emergency Dispatch',
    'infoViews.serviceResponse': 'Service Response Time',
    'infoViews.power': 'Power',
    'infoViews.water': 'Water',
    'infoViews.waste': 'Waste',
    'infoViews.health': 'Health',
    'infoViews.education': 'Education',
    'infoViews.fireSafety': 'Fire Safety',
    'infoViews.policeCrime': 'Police & Crime',
    'infoViews.landValue': 'Land Value',
    'infoViews.pollution': 'Pollution',
    'infoViews.noise': 'Noise',
    'infoViews.happiness': 'Happiness',
    'infoViews.incidents': 'Incidents',
    'infoViews.disasters': 'Natural Disasters',
    'infoViews.naturalResources': 'Natural Resources',
    'infoViews.hydrology': 'Surface Water & Flooding',
    'infoViews.districts': 'District Policies',
    'infoViews.resourcesLegend': 'Resources Legend',
    'infoViews.fertileLand': 'Fertile Land (Farming)',
    'infoViews.forest': 'Forest (Timber Industry)',
    'infoViews.oreMinerals': 'Ore Minerals (Mining)',
    'infoViews.oilReserves': 'Oil Reserves (Drilling)',
    'infoViews.responseTime': 'Response time (minutes)',
    'infoViews.transitRouteNetwork': 'Transit route network',
    'infoViews.emergencyDispatchPaths': 'Emergency dispatch paths',
    'infoViews.fire': 'Fire',
    'infoViews.medical': 'Medical',
    'infoViews.police': 'Police',
    'metric.households': 'Households',
    'metric.householdSatisfaction': 'Household Satisfaction',
    'metric.treasury': 'Treasury',
    'metric.landUseSuitability': 'Land-use Suitability',
    'metric.persistentParcels': 'Persistent Parcels',
    'metric.developedPrivateLots': 'Developed / Private Lots',
    'metric.averageLotSize': 'Average Lot Size',
    'metric.mixedUseBlocks': 'Mixed-use Blocks',
    'metric.mixedUseFloors': 'Mixed-use Floors',
    'metric.mixedUseJobs': 'Mixed-use Jobs',
    'metric.netIncome': 'Net Income',
    'metric.municipalDebt': 'Municipal Debt',
    'metric.activeBackgroundRegions': 'Active / Background Regions',
    'metric.recoveryProjects': 'Recovery Projects',
    'metric.tradeContracts': 'Trade Contracts',
    'metric.importCapacity': 'Import Capacity',
    'metric.exportCapacity': 'Export Capacity',
    'metric.exportRevenue': 'Export Revenue',
    'metric.citySpecialization': 'City Specialization',
    'metric.activeDisasters': 'Active Disasters',
    'metric.recoveryLoad': 'Recovery Load',
    'metric.roadRecoveryTick': 'Road Recovery / Tick',
    'metric.resolvedThisTick': 'Resolved This Tick',
    'metric.happinessPenalty': 'Happiness Penalty',
    'metric.seasonWeather': 'Season / Weather',
    'metric.temperature': 'Temperature',
    'metric.precipitation': 'Precipitation',
    'metric.population': 'Population',
    'metric.happiness': 'Happiness',
    'metric.totalHouseholds': 'Total Households',
    'metric.employedWorkforce': 'Employed Workforce',
    'metric.employedCitizens': 'Employed Citizens',
    'metric.unemploymentRate': 'Unemployment Rate',
    'metric.avgDailySalary': 'Avg Daily Salary',
    'settings.title': 'Game Settings',
    'settings.gameplay': 'Gameplay',
    'settings.graphics': 'Graphics',
    'settings.audio': 'Audio',
    'settings.controls': 'Controls',
    'settings.accessibility': 'Accessibility',
    'settings.rules': 'Gameplay Rules',
    'settings.difficulty': 'Difficulty',
    'settings.autosave': 'Autosave',
    'settings.graphicsTitle': 'Graphics Settings',
    'settings.shadowQuality': 'Shadow Quality',
    'settings.antiAliasing': 'Anti-aliasing',
    'settings.renderScale': 'Render Scale',
    'settings.dayNightCycle': 'Day/Night Cycle',
    'settings.trafficDensity': 'Traffic Density',
    'settings.vegetationDensity': 'Vegetation Density',
    'settings.vsyncTitle': 'V-Sync & frame cap',
    'settings.vsyncInfo': 'Managed by the browser through requestAnimationFrame. The manual option stays hidden until the renderer supports a real frame cap.',
    'settings.audioTitle': 'Audio Settings',
    'settings.sfxVolume': 'Sound Effects Volume',
    'settings.musicVolume': 'Music & Ambience Volume',
    'settings.soundscapeTitle': 'City Soundscape',
    'settings.soundscapeInfo': 'Music Volume controls the procedural music pad and city ambience. Effects Volume controls clicks, building, demolition, and sirens.',
    'settings.controlsTitle': 'Controls & Keyboard Shortcuts',
    'settings.accessibilityTitle': 'Accessibility & Support',
    'settings.language': 'Language',
    'settings.uiScale': 'UI Scale',
    'settings.reducedMotion': 'Reduce Motion',
    'settings.adaptiveQuality': 'Adaptive Quality',
    'settings.experimental': 'Experimental Features',
    'settings.highContrast': 'High Contrast',
    'settings.colorblind': 'Color Vision Support',
    'settings.none': 'None',
    'settings.qualityNote': 'Adaptive Quality lowers visual detail when frame rate drops. Simulation results and economy numbers do not change.',
    'settings.exportDiagnostic': 'Export Diagnostic Report',
    'settings.reset': 'Reset Settings',
    'settings.repeatTutorial': 'Repeat Guide',
    'settings.toggleOn': 'on',
    'settings.toggleOff': 'off',
    'settings.easy': 'Easy (Bonus Funds & Growth)',
    'settings.normal': 'Normal (Standard Balance)',
    'settings.hard': 'Hard (Strict Utility & Demands)',
    'settings.applyClose': 'Apply & Close',
    'missions.title': 'City Objectives & Badges',
    'missions.subtitle': 'Milestone Challenges & Achievements',
    'missions.tab': 'Objectives & Grants',
    'achievements.tab': 'Civic Achievements',
    'scenarios.tab': 'Campaign Scenarios',
    'missions.grant': 'Grant',
    'missions.completed': 'Completed',
    'missions.claim': 'Claim Reward',
    'missions.progress': 'In Progress',
    'scenario.start': 'Start',
    'scenario.active': 'Active',
    'policies.title': 'Municipal Policy Directives',
    'policies.subtitle': 'Enact Ordinance · Active Policies',
    'policies.free': 'No Upkeep',
    'policies.apply': 'Enact Policy',
    'policies.locked': 'Locked',
    'policies.benefits': 'Benefits',
    'policies.costBearer': 'Cost bearer',
    'policies.ruleEffect': 'Rule engine effect',
    'policies.longTerm': 'Long term',
    'policies.metric': 'Evaluation metric',
    'tech.title': 'City Tech Tree & Innovations',
    'tech.subtitle': 'Research Prerequisite Tech · Current Milestone',
    'tech.requires': 'Requires',
    'tech.researched': 'Researched',
    'tech.prerequisiteLocked': 'Prerequisite Locked',
    'tech.milestoneLocked': 'Milestone Locked',
    'tech.insufficientFunds': 'Insufficient Funds',
    'tech.research': 'Research Tech',
    'districts.title': 'District Planner',
    'districts.subtitle': 'Spatial identity & local policy',
    'districts.create': 'Create district',
    'districts.name': 'Name',
    'districts.localPolicy': 'Local policy',
    'districts.radius': 'Radius',
    'districts.place': 'Place on Map',
    'districts.existing': 'Existing districts',
    'districts.total': 'total',
    'districts.empty': 'No districts yet. Create one to give a city area local identity and policy.',
    'inspector.title': 'Tile Inspection',
    'inspector.growthAdvisor': 'Growth Advisor',
    'inspector.occupancy': 'Occupancy',
    'inspector.demand': 'Demand',
    'inspector.capacity': 'Capacity',
    'inspector.density': 'Density',
    'inspector.bulldoze': 'Bulldoze Tile',
    'inspector.intersectionControl': 'Intersection Control',
    'inspector.auto': 'Auto',
    'inspector.signal': 'Signal',
    'inspector.stopSigns': 'Stop signs',
    'inspector.roundabout': 'Roundabout',
    'metric.consumerDemand': 'Consumer Demand',
    'metric.goodsDemand': 'Goods Demand',
    'metric.officeDemand': 'Office Demand',
    'metric.freightDemand': 'Freight Demand',
    'traffic.commuteFlow': 'Traffic & Commute Flow',
    'traffic.averageFlow': 'Average Traffic Flow',
    'traffic.congestionIndex': 'Congestion Index',
    'traffic.avgCommuteTime': 'Avg Commute Time',
    'traffic.parkingDemand': 'Parking Demand',
    'traffic.transitNetwork': 'Public Transit Network',
    'metric.desirability': 'Desirability',
    'metric.preparedness': 'Disaster Preparedness',
    'scenario.completed': 'Completed',
    'scenario.monitoring': 'Monitoring',
    'spec.balanced': 'Balanced',
  },
};

export function createLocalizationCatalog(language: SupportedLanguage = 'id'): LocalizationCatalog {
  if (language === 'en') {
    return {
      language,
      fallbackLanguage: 'id',
      messages: { ...DEFAULT_LOCALIZATION.fallbackMessages },
      fallbackMessages: { ...DEFAULT_LOCALIZATION.messages },
    };
  }
  return {
    ...DEFAULT_LOCALIZATION,
    messages: { ...DEFAULT_LOCALIZATION.messages },
    fallbackMessages: { ...DEFAULT_LOCALIZATION.fallbackMessages },
  };
}

export function translate(catalog: LocalizationCatalog, key: string, variables: Record<string, string | number> = {}): string {
  const template = catalog.messages[key] ?? catalog.fallbackMessages[key] ?? key;
  return Object.entries(variables).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template);
}
