import { TransitLine } from './types';
import { isTransitLineOperating, TransitVehicleAgent } from './transit';

export interface TransitRouteGeometry {
  line: TransitLine;
  path: [number, number][];
  usesVehiclePath: boolean;
  operating: boolean;
}

export interface TransitMapBounds {
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
}

/**
 * Chooses the authoritative road path generated by transit simulation when a
 * vehicle exists; before the first operating tick it falls back to the
 * configured stop chain so the planner is still visible and editable.
 */
export function deriveTransitRouteGeometry(
  lines: TransitLine[],
  vehicles: TransitVehicleAgent[],
  timeOfDay = 12,
): TransitRouteGeometry[] {
  return lines
    .filter((line) => line.stops.length > 0)
    .map((line) => {
      const vehiclePath = vehicles.find((vehicle) => vehicle.lineId === line.id)?.path;
      return {
        line,
        path: vehiclePath && vehiclePath.length > 1 ? vehiclePath : line.stops,
        usesVehiclePath: Boolean(vehiclePath && vehiclePath.length > 1),
        operating: line.active && isTransitLineOperating(line, timeOfDay),
      };
    });
}

export function calculateTransitMapBounds(routes: TransitRouteGeometry[]): TransitMapBounds {
  const points = routes.flatMap((route) => route.path);
  if (points.length === 0) return { minX: 0, maxX: 1, minY: 0, maxY: 1 };
  return {
    minX: Math.min(...points.map(([x]) => x)),
    maxX: Math.max(...points.map(([x]) => x)),
    minY: Math.min(...points.map(([, y]) => y)),
    maxY: Math.max(...points.map(([, y]) => y)),
  };
}

export function projectTransitMapPoint(
  [x, y]: [number, number],
  bounds: TransitMapBounds,
  width = 300,
  height = 140,
  padding = 12,
): [number, number] {
  return [
    padding + ((x - bounds.minX) / Math.max(1, bounds.maxX - bounds.minX)) * (width - padding * 2),
    padding + ((y - bounds.minY) / Math.max(1, bounds.maxY - bounds.minY)) * (height - padding * 2),
  ];
}
